---
  - name: installing metricbeat
    hosts: webservers
    become: yes
    tasks:

     - name: download metricbeat deb
       command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.2-amd64.deb
 
     - name: install metricbeat deb
       command: sudo dpkg -i  metricbeat-7.6.2-amd64.deb

     - name: drop in metricbeat.yml
       copy:
         src: /etc/metricbeat/metricbeat.yml
         dest: /etc/metricbeat/metricbeat.yml

     - name: enable and configure system module
       command: sudo metricbeat modules enable docker

     - name: setup metricbeat
       command: sudo metricbeat setup

     - name: start metricbeat service
       command: sudo service metricbeat start

     - name: enable service metricbeat on boot
       systemd:
         name: metricbeat
         enabled: yes

